#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
echo "Running pre-commit hook"

echo "Running ESLint 🧹"

cd Frontend/ecommerce
echo "Running prettier 🎨"
echo "Formatting files:"
npx prettier --write . | grep -v "unchanged" | xargs -I{} echo "- {}"

npm run lint --fix .